language: go
sudo: false
go:
- 1.11.2
script:
- echo "run unit tests"
- make test
- echo "build app binaries"
- make app-linux
- make app-mac
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
    file: 
    - parameters-util-linux
    - parameters-util-mac
  on:
    repo: alext234/parameters-util
    tags: true
